spring:
  application:
    name: config-server
  profiles:
    active: native #использование конфигов из classpath
  main:
    log-startup-info: false
    banner-mode: off
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/core/{application}
            - classpath:config/infra/{application}
            - classpath:config/stats/{application}
  eureka:
    client:
      service-url:
        default-zone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/

server:
  port: 0 # random port number