services:
  stats-db:
    image: postgres:16.1
    container_name: ewm_stats_db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "6541:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d stats" ]
      interval: 10s
      timeout: 5s
      retries: 5

  main-db:
    image: postgres:16.1
    container_name: ewm_main_db
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "6542:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d main" ]
      interval: 10s
      timeout: 5s
      retries: 5