services:
  stats-db:
    image: postgres:16.1
    container_name: ewm_stats_db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "6541:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d stats" ]
      interval: 10s
      timeout: 5s
      retries: 5

  main-db:
    image: postgres:16.1
    container_name: ewm_main_db
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "6542:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d main" ]
      interval: 10s
      timeout: 5s
      retries: 5

  main-db-init:
    image: postgres:16.1
    container_name: main-db-init
    depends_on:
      main-db:
        condition: service_healthy
    environment:
      PGPASSWORD: password
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql -h localhost -p 5432 -U user -d main -v ON_ERROR_STOP=1 <<-EOSQL
        CREATE DATABASE ewm_event_db;
        CREATE DATABASE ewm_event_request_db;
        CREATE DATABASE ewm_user_db;
        CREATE DATABASE ewm_extra_func_db;
        EOSQL
        echo "Databases created successfully!"