spring:
  application:
    name: stats-server
  config:
    import: "configserver:" # external configuration
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 2000
  eureka:
    client:
      service-url:
        default-zone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
    instance:
      prefer-ip-address: true
      hostname: localhost
      instance-id: "${spring.application.name}:${random.value}"
      lease-renewal-interval-in-seconds: 10