server:
  port: 8080

spring:
  application:
    name: gateway-server
  main:
    log-startup-info: false
    banner-mode: off
  cloud:
    gateway:
      discovery.locator.enabled: true # использование Discovery Service
      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**

        - id: ewm_event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**, /categories/**, /users/*/events/**, /admin/events/**, /events/**

        - id: ewm_event_request_service_route
          uri: lb://event-request-service
          predicates:
            - Path=/user/*/requests/**

        - id: ewm_user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: ewm_extra_func_service_route
          uri: lb://extra-func-service
          predicates:
            - Path=/admin/compilations/**, /compilations/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, mappings, gateway
  endpoint:
    gateway:
      enabled: true # для просмотра gateway/routes

logging:
  level:
    root: INFO