spring:
  application:
    name: main-service
  config:
    import: "configserver:" # external configuration
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true # ?????? ???? config-server ??????????
      retry:
        use-random-policy: true # ????? ????????? «????????? ???????????????? ????????»
        max-interval: 2000 # max ???????? ????? ?????????
  eureka:
    client:
      service-url:
        default-zone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
    instance: # ???????? ??????????? ???????? ???????
      prefer-ip-address: true # ?????????????? ???? ?????? ?? IP-??????
      hostname: localhost
      instance-id: "${spring.application.name}:${random.value}" # ?????????? ID ??????????? ?????????? ???????
      lease-renewal-interval-in-seconds: 10 # interval health check?? ? eureka

# Server settings
#server.port=8080
#
#spring.datasource.url=jdbc:postgresql://localhost:6542/main
#spring.datasource.username=user
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA settings
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#
## Logging
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.ewm=DEBUG
#
#logging.level.org.springframework.boot.autoconfigure=DEBUG
#logging.level.org.springframework.context=DEBUG